# Generated by Django 5.0 on 2023-12-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='third_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество'),
        ),
    ]
