# Generated by Django 5.0 on 2023-12-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
